FROM python:3.9.12

WORKDIR /usr/src/app


# install lsb-release
RUN apt-get update && apt-get install -y lsb-release && apt-get clean all

# import GPG key
RUN wget https://download.tinkerforge.com/apt/$(lsb_release -is | tr [A-Z] [a-z])/archive.key -q -O - | apt-key add -

# add apt repo
RUN sh -c "echo 'deb https://download.tinkerforge.com/apt/$(lsb_release -is | tr [A-Z] [a-z]) $(lsb_release -cs) main' > /etc/apt/sources.list.d/tinkerforge.list"
RUN apt update

# install requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 4223

CMD [ "python", "./main.py" ]